### ISSUE TITLE
Destination "unrecognized argument"

### ISSUE THREAD

**Issue by fvonkriegenbergh** [martinsik/minecraft-dynmap-timemachine#12]
When I try to create an image, I get an error saying the dest argument is unrecognized. Even directly using the example command:
"dynmap-timemachine.py http://map.majncraft.cz/ world surface \ [3300,65,-2630] [3,2] 0 majncraft.test.png"
gives me:
"dynmap-timemachine.py: error: unrecognized arguments: majncraft.test.png"

**Comment by FedUpWith-Tech** [comment]
The readme is wrong, do this instead:
"dynmap-timemachine.py http://map.majncraft.cz/ world surface [3300,65,-2630] [3,2] 0 majncraft.test.png"

**Comment by fvonkriegenbergh** [comment]
Thanks, it works now!
